#!/bin/sh
#
# Copyright (c) 1994 The University of Utah and
# the Computer Systems Laboratory (CSL).  All rights reserved.
#
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright
# notice and this permission notice appear in all copies of the
# software, derivative works or modified versions, and any portions
# thereof, and that both notices appear in supporting documentation.
#
# THE UNIVERSITY OF UTAH AND CSL ALLOW FREE USE OF THIS SOFTWARE IN ITS "AS
# IS" CONDITION.  THE UNIVERSITY OF UTAH AND CSL DISCLAIM ANY LIABILITY OF
# ANY KIND FOR ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
#
# CSL requests users of this software to return to csl-dist@cs.utah.edu any
# improvements that they make and grant CSL redistribution rights.
#
#      Author: Bryan Ford, University of Utah CSL
#

# Many of the files in this directory are taken verbatim
# from the Linux kernel source distribution.
# This script updates these source files from a Linux source tree
# whose location is specified by the first argument
# (e.g. `update-from-linux /usr/src/linux').

if [ $# -eq 0 ]; then
	echo "Usage: $0 <linux-kernel-srcdir>"
	echo "  e.g. $0 /usr/src/linux"
	exit 1
fi


# This list is sorted for convenience;
# please keep it that way.

cp $1/include/linux/config.h .
cp $1/include/linux/segment.h .
cp $1/zBoot/crypt.h .
cp $1/zBoot/gzip.h .
cp $1/zBoot/inflate.c .
cp $1/zBoot/lzw.h .
cp $1/zBoot/unzip.c .

